### ISSUE TITLE
Solaris VM very out of date

### ISSUE THREAD

**Issue by ghost** [vmactions/solaris-vm#38] opened 2024-03-11 20:57 UTC
Hi, the version of Solaris on the VM needs updating as many recent packages cannot be installed because they are not present in the package repo of this old version (it predates 2020). An example is the meson build system which was added to the Solaris pkg repo in 2020. A simple command will do it (run as root):
`pkg update` 
Followed by a reboot. The version will now be 11.4.42.
Thanks for maintaining this very useful repo.

**Comment by Neilpang** [comment] 2024-03-11 22:22
I will make a new release tomorow.

please just wait for the new build to release.

**Comment by dgsga** [comment] 2024-03-12 20:10
That's great, thank you.

**Comment by mrpippy** [comment] 2024-05-31 22:17
Was this completed? I ran `shell-solaris` and got a not-updated 11.4 system.

Maybe the new image could be built off of the 11.4.42 (CBE) images (https://blogs.oracle.com/solaris/post/announcing-the-first-oracle-solaris-114-cbe), rather than needing to update an 11.4 system?

**Comment by Neilpang** [comment] 2024-06-01 16:42
The CBE  was released on March 2, 2022.
but our image was built on  Jul 11, 2022
https://github.com/vmactions/solaris-download/releases

I think we are the latest.

**Comment by dgsga** [comment] 2024-06-02 19:31
The version of Solaris used in the VM image is definitely **not** the latest. The CBE image (V1019840-01.iso) is version 11.4.42, sol-11_4-text-x86.iso installs an earlier version of 11.4. This is why the vmactions image urgently needs to be updated

**Comment by whoschek** [comment] 2024-07-08 20:10
I'd also love to see a more recent Solaris version in the VM. The current VM has python-3.4 whereas I need at least python-3.7. I tried all kinds of workarounds to install python-3.7 - all without success, except that a 'pkg update --accept; reboot' resolves the issue as it auto upgrades python to 3.7 (as I verified in your very helpful shell-solaris tool). Unfortunately the reboot step in a gibhub CI test job sends the job into nowhere so that doesn't work either. solaris-vm is a fantastic tool but unfortunately there's only a solaris VM version available that's too old to be practical for many uses.

**Comment by Neilpang** [comment] 2024-07-09 10:42
@whoschek 
I had tried to upgrade the vm, but it was just not easy for me to download the latest ISO file from the official oracle website.  I guess that it was because my country is restricted.  I had tried several times, but no success.

We first need to download the ISO file by this project: https://github.com/vmactions/solaris-download
Then we need to upgrade the builder project to build the vm:  https://github.com/vmactions/solaris-builder
Last, we can update this solaris-vm project to use  the latest built vm images.

Anyway, I will try more once I have time.

**Comment by rdmark** [comment] 2024-07-09 12:33
@Neilpang Please let me know if there is anything I can do to assist. Thank you for all your hard work! Your VMs have helped us catch real bugs.

**Comment by bradh352** [comment] 2024-07-16 19:49
I think the current vm image the solaris-builder is using can just be upgraded.  I see it links to https://github.com/vmactions/solaris-download/releases/download/v0.0.2/sol-11_4-text-x86.iso
for the install.  I think just adding a step that performs `pkg upgrade --accept`  in `hooks/postBuild.sh`

**Comment by Neilpang** [comment] 2024-07-19 02:22
@bradh352  I tried, it's not working.  the vm is down.

**Comment by Neilpang** [comment] 2024-07-19 02:23
https://github.com/vmactions/solaris-builder/commit/fe3d64c0a78257a684b6b30fc0511de565652ae6

**Comment by bradh352** [comment] 2024-07-19 13:25
Looking at the latest build is very promising. Its failing due to not being able to connect to OpenCSW, which honestly should NOT be used these days at all.  The VM built, just the post-build actions failed running within solaris.  I'm not entirely sure why it couldn't resolve opencsw, it resolves fine for me, so its possible the networking isnt' fully online, either that or the DNS isn't set properly.  Maybe adding  'ifconfig -a' and 'cat /etc/resolv.conf' to the script would provide some insight.

**Comment by bradh352** [comment] 2024-07-24 09:58
@Neilpang any chance you had time to review https://github.com/vmactions/solaris-builder/pull/3 ?  That should close this issue.

**Comment by bradh352** [comment] 2024-08-11 15:05
@Neilpang any update?

**Comment by Neilpang** [comment] 2024-08-11 15:45
I will check it later

**Comment by gansm** [comment] 2024-08-17 21:42
I am also very interested in upgrading to Solaris 11.4.42.0.0.111.0. With the current VM, I can only use GCC version 7.3.

As the developer of [FINAL CUT](https://github.com/gansm/finalcut), I would like to port the code to C++17, but I do not want to start with a compiler that only covers 95% of the C++17 standard. With the current Solaris release, I could use GCC 11.2.

**Comment by Neilpang** [comment] 2024-09-07 06:04
I just updated to the latest iso. can you please try again, and let me know if it's ok for you?

**Comment by rdmark** [comment] 2024-09-07 06:56
@Neilpang Unfortunately, v1.0.3 is not yet at the latest Solaris patch version.

If you run `pkg list entire` on your v1.0.3 image:

```
entire                                            11.4-11.4.0.0.1.15.0       i--
```

However, a fully updated Solaris system at the time of writing should be at:

```
entire                                            11.4-11.4.42.0.0.111.0     i--
```

**Comment by Neilpang** [comment] 2024-09-07 17:05
@rdmark   where to download the latest ISO file including the updates?

**Comment by bradh352** [comment] 2024-09-08 00:29
I cached it here https://github.com/bradh352/vmactions-solaris-builder/releases/download/2.0.0/solaris-11.4.42.111.0-x86-cbe.iso

**Comment by bradh352** [comment] 2024-09-08 00:33
doesn't look like you incorporated any of my changes from the PR

**Comment by bradh352** [comment] 2024-09-08 00:47
I just resolved the recently introduced merge conflicts, its building now in my fork .... 

11.4: https://github.com/bradh352/vmactions-solaris-builder/actions/runs/10755633076/job/29827586665

11.4-gcc: https://github.com/bradh352/vmactions-solaris-builder/actions/runs/10755633076/job/29827586786

**Comment by bradh352** [comment] 2024-09-08 01:38
FYI, built fine:
```
-rw-r--r-- 1 runner docker 1.5G Sep  8 01:21 solaris-11.4.qcow2.xz
-rw-r--r-- 1 runner docker 2.0G Sep  8 01:37 solaris-11.4-gcc.qcow2.xz.0
-rw-r--r-- 1 runner docker 241M Sep  8 01:37 solaris-11.4-gcc.qcow2.xz.1
```

**Comment by Neilpang** [comment] 2024-09-08 15:31
fixed.
please use the latest "11.4-cbe" tag.

**Comment by whoschek** [comment] 2024-09-08 15:46
Failed for me with the error msg below. Same job passed for tag "11.4". Details are here: https://github.com/whoschek/wbackup-zfs/actions/runs/10761127241/job/29839954277

Errors were encountered when attempting to contact repository for publisher 'solaris'.
  Unable to contact valid package repository: https://pkg.oracle.com/solaris/support/
  Encountered the following error(s):
    Framework error: code: E_SSL_CONNECT_ERROR (35) reason: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
  URL: 'https://pkg.oracle.com/solaris/support'
  pkg install: The following pattern(s) did not match any allowable packages.  Try
  using a different matching pattern, or refreshing publisher information:
  	gcc

**Comment by bradh352** [comment] 2024-09-08 19:28
Yep, none of my changes were merged in which can be viewed in my PR here:
https://github.com/vmactions/solaris-builder/pull/3/files

Looks like the only change made was the ISO in use really.

At a minimum the repository has to be fixed by running:
```
pkg set-publisher -G'*' -g http://pkg.oracle.com/solaris/release/ solaris
```

Due to a known issue in CBE referenced here: https://blogs.oracle.com/solaris/post/building-open-source-software-on-oracle-solaris-114-cbe-release

I'll try to merge the latest changes into my PR in the hopes it gets accepted.

**Comment by bradh352** [comment] 2024-09-08 19:35
Also this PR https://github.com/vmactions/base-builder/pull/1/ for the base builder needs to be merged first

**Comment by whoschek** [comment] 2024-09-10 18:01
Ok, that fixed it. Thx!

**Closed** 2024-09-10 18:55 UTC

**Comment by bradh352** [comment] 2024-09-10 19:43
I think the only additional thing needed once the new solaris packages are published is for the 11.4-gcc that was split into multiple files, the fetching needs to pull them in https://github.com/vmactions/base-vm/blob/main/run.sh#L92 :
```sh
if [ ! -e "$ovafile" ]; then
    echo "Downloading $OVA_LINK"
    axel -n 8 -o "$ovafile" -q "$OVA_LINK"
    echo "Download finished, extract"
    xz -d $ovafile
    echo "Extract finished"
  fi
```

I'm going to assume `$OVA_LINK` will be defined as a space separated list of files to be downloaded, something like:
```
OVA_LINK="https://github.com/vmactions/solaris-builder/releases/download/v${BUILDER_VERSION}/solaris-${VM_RELEASE}.qcow2.xz https://github.com/vmactions/solaris-builder/releases/download/v${BUILDER_VERSION}/solaris-${VM_RELEASE}.qcow2.xz.1"
```

Looks like you use axel to try to speed up downloads, but it doesn't seem to have many options so I don't know how to do it with that utility.

```sh
if [ ! -e "$ovafile" ]; then
    for url in $OVA_LINK ; do
        echo "Downloading $url"
        wget -O - $url >> "$ovafile"
    done
    echo "Download finished, extract"
    xz -d $ovafile
    echo "Extract finished"
  fi
```

**Comment by Neilpang** [comment] 2024-09-10 20:55
please try with the latest release.  it uses CBE as the default image. 
Just use tag: `11.4`

**Comment by bradh352** [comment] 2024-09-10 21:16
trying it now, but using 11.4-gcc which uses .xz and .xz.1 ... https://github.com/bradh352/c-ares/actions/runs/10800672852/job/29959205437

**Comment by bradh352** [comment] 2024-09-10 22:01
looks good to me, error was my fault for forgetting to tell it to install gdb :)

**Comment by bradh352** [comment] 2024-09-10 22:28
i've merged its use into c-ares ... works great, thanks!
https://github.com/c-ares/c-ares/actions/runs/10801422779/job/29961546247

on a different topic, i wonder if it would make sense to consider the use of zstd instead of xz for faster decompression time?

**Comment by Neilpang** [comment] 2024-09-11 07:16
@bradh352   yes,   how faster is it?

**Comment by bradh352** [comment] 2024-09-11 10:43
there's a graph on this page:
https://facebook.github.io/zstd/

xz uses lzma which is listed on the bar graph, looks like zstd is about 13x faster at decompression

**Comment by rdmark** [comment] 2024-09-11 13:07
Confirmed that v1.0.6 works for the needs of the Netatalk CI workflow as well! Thank you to everyone who made this happen.

**Comment by whoschek** [comment] 2024-09-11 21:19
Integrated it into wbackup-zfs. Works very well! 
@bradh352 , @Neilpang Thanks for all the hard work, guys!

**Comment by Neilpang** [comment] 2024-09-15 17:23
@bradh352   fixed,  the lastest release is using zstd now.   the time cost is reduced by about 1min

**Comment by bradh352** [comment] 2024-09-15 18:41
nice, i see my latest c-ares runs are using it.    Comparing 2 runs, I see the xz run took 7:52, and the zstd run took 6:59, so yep, right about a minute difference.
